global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - user-service:8080

  - job_name: finance-core-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - finance-core-service:8081

  - job_name: reporting-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - reporting-service:8082
